"""
Tutor Schemas — Structured Responses and Payloads for Q-Trace Tutor.
===================================================================
Owner:   Rajeswari (ai-pedagogy track)
Card:    AI-5
Contract: board/contracts/flight-recorder-tutor.md v1
"""

from __future__ import annotations

import uuid
from typing import List, Optional
from pydantic import BaseModel, ConfigDict, Field

from app.services.tutor.badge import TutorBadge


class TutorStep(BaseModel):
    """Step in an evidence-grounded tutor explanation."""
    model_config = ConfigDict(extra="ignore")
    title: str = Field(..., description="Short headline for the step")
    body: str = Field(..., description="Trace-grounded explanation body")
    evidenceKeys: List[str] = Field(
        default_factory=list,
        description="Dot-path references into StateTrace (e.g., stateTrace.0.basisProbabilities)",
    )


class NumericalClaim(BaseModel):
    """Specific numerical claim asserted by the tutor."""
    model_config = ConfigDict(extra="ignore")
    claim: str = Field(..., description="String stating the numerical value, e.g. 'P(00)=0.5'")
    evidenceKey: str = Field(
        ...,
        description="Exact StateTrace dot-path containing the verified numerical value",
    )


class StructuredTutorResponse(BaseModel):
    """Full structured tutor explanation payload conforming to contract v1."""
    model_config = ConfigDict(extra="ignore")
    responseId: str = Field(
        default_factory=lambda: f"tr_{uuid.uuid4().hex[:8]}",
        description="Unique identifier for this tutor response",
    )
    intent: str = Field(..., description="Pedagogical intent")
    summary: str = Field(..., description="Synthesized summary of divergence/advice")
    steps: List[TutorStep] = Field(..., description="Step-by-step grounded breakdown")
    numericalClaims: List[NumericalClaim] = Field(
        default_factory=list,
        description="Verifiable claims matching simulation evidence",
    )
    repairChallengeId: str = Field(
        ..., description="Recommended follow-up repair challenge ID"
    )
    fallbackUsed: bool = Field(
        default=False,
        description="True if curated offline fallback was used; False if generated by cloud model",
    )
    model: str = Field(
        ..., description="Name of the model or provider used ('DEMO_FALLBACK' if offline fallback)"
    )
    safetyNote: str = Field(
        default="Explanation is grounded in this Simulation Run; it is not a hardware claim.",
        description="Required disclaimer regarding simulation vs physical quantum hardware",
    )
    badge: Optional[TutorBadge] = Field(
        default=None,
        description="Optional UI badge indicating mode and failover resilience state",
    )
